<?php

namespace Application\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithSociete()
    {
        $dql = "SELECT c, s
                FROM Application\Entity\Contact c
                LEFT JOIN c.societe s
                ORDER BY s.nom, c.prenom, c.nom";

        $query = $this->_em->createQuery($dql);

        return $query->getResult();
    }
}
